server:
  port: 9000
  servlet:
    context-path: /app
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vehicles
    username: benefits
    password: ben0147
  main:
    banner-mode: log
  #    allow-circular-references: true
  application:
    name: Vehicles
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
