server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: api-gateway
  cloud.gateway:
    discovery.locator:
      enabled: true
      lowerCaseServiceId: true
    routes:
      - id: users-status-check
        uri: lb://users-web
        predicates:
          - Path=/users/**
          - Method=GET
          - Header=Authorization, Bearer (.*)
        filters:
          - RemoveRequestHeader=Cookie
      - id: users-account
        uri: lb://users-accounts-web
        predicates:
          - Path=/account/**
        filters:
          - RemoveRequestHeader=Cookie


